<?php

return [
    'templates'         => [
        'fields' => [
            'name' => 'name',
            'text' => 'text',
        ],
        'attr'   => [
            'name' => 'Название',
            'text' => 'Текст',
        ],
    ],
    'description_makro' => [
        '${code}'                => 'Код заказа',
        '${lot_number}'          => 'Номер партии',
        '${order_number}'        => 'Номер заказа',
        '${fio}'                 => 'ФИО клиента',
        '${index}'               => 'Почтовый индекс',
        '${geo}'                 => 'Область, край, республика',
        '${district}'            => 'Район отправления',
        '${address}'             => 'Адрес',
        '${fio_relatives}'       => 'ФИО родителя клиента',
        '${phone_relatives}'     => 'Телефон родителя клиента',
        '${notes}'               => 'Примечания к заказу',
        '${track}'               => 'Трек номер заказа',
        '${info}'                => 'Дополнительная информация',
        '${payment_state_name}'  => 'Статус оплаты',
        '${status_stage_name}'   => 'Стадия отправления заказа',
        '${status_state_name}'   => 'Статус отправления заказа',
        '${payment_sum}'         => 'Сумма заказа',
        '${payment_date}'        => 'Дата операции оплаты',
        '${payment_place_index}' => 'Индекс отделения',
    ],
    'makro_replace'     => [
        '${code}'                => 'code',
        '${lot_number}'          => 'lot_number',
        '${order_number}'        => 'order_number',
        '${fio}'                 => 'fio',
        '${index}'               => 'index',
        '${geo}'                 => 'geo',
        '${district}'            => 'district',
        '${address}'             => 'address',
        '${fio_relatives}'       => 'fio_relatives',
        '${phone_relatives}'     => 'phone_relatives',
        '${notes}'               => 'notes',
        '${track}'               => 'track',
        '${info}'                => 'info',
        '${payment_state}'       => 'payment_state',
        '${payment_state_name}'  => 'payment_state_name',
        '${status_stage_name}'   => 'status_stage_name',
        '${status_state_name}'   => 'status_state_name',
        '${payment_sum}'         => 'payment_sum',
        '${payment_date}'        => 'payment_date',
        '${payment_place_index}' => 'payment_place_index',
    ],
];
